PROJECT_NAME: Medpoint
PROJECT_ID: eylvbwzcbnqpapumtfdj
DEPLOYMENT_TARGET: cloud

MODE: bff
ACCESS_TOKEN: sbp_23067a77b4c5997668596d88ca355cc40881b609
ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV5bHZid3pjYm5xcGFwdW10ZmRqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxMTg5NDcsImV4cCI6MjA1OTY5NDk0N30.Jlz5TzTl_OH4s5jw8Kd6OOYdfq6OqtEXN0V_1U-Z32c
SERVICE_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV5bHZid3pjYm5xcGFwdW10ZmRqIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0NDExODk0NywiZXhwIjoyMDU5Njk0OTQ3fQ.unacUzKdH02LL5zHP633FApt0EF6Zqt_6nACE67Snvc

SUPABASE_API_URL: https://api.supabase.com
SUPABASE_API_BASE_PATH: 
SUPABASE_API_TOKEN: 
SUPABASE_API_TOKEN_TYPE: 
SUPABASE_PUBLIC_URL: https://eylvbwzcbnqpapumtfdj.supabase.co
SERVER_HOST: 127.0.0.1
SERVER_PORT: 8002
SERVER_DNS: 

ENVIRONMENT: development
VERSION: 1.0.0

ALLOWED_TABLES: '*'
SCHEDULE_STATUS: 'off'

BREAKER_ENABLE: false

TRACE_ENABLE: false
TRACE_COLLECTOR: 
TRACE_COLLECTOR_ENDPOINT: 

MAX_SERVER_REQUEST_BODY_SIZE: 8388608

CORS_ALLOWED_ORIGINS:
CORS_ALLOWED_METHODS:
CORS_ALLOWED_HEADERS:
